apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Name }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: {{ .Server }}
  sourceRepos:
    - '*'
  {{- if .ProjectRoles }}
  roles:{{ "\n" }}
  {{- range .ProjectRoles }}
  - name: {{ .Name }}
    {{- if .Description }}
    description: {{ .Description }}
    {{- end }}
    policies:
    {{- range .Policies }}
    - {{ . }}
    {{- end }}
    {{- if .JwtTokens }}
    jwtTokens:
    {{- range .JwtTokens }}
    - iat: {{ . }}
    {{- end }}
    {{- end }}
  {{- end }}
  {{- end }}
